spring:
  application:
    name: SpringAIProject
  server:
    port: 8080
  ai:
    openai:
      api-key: ${API_KEY}
      chat:
      options:
        model: gpt-5

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/openai
    model: gemini-3-flash-preview
    apikey: ${API_KEY}






















